spring.application.name=foodiesapi

#mongodb configuration
spring.data.mongodb.uri=mongodb://localhost:27017/foodies

#aws s3 configuration
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=ap-southeast-2
aws.s3.bucketname=foodies-foods-babyshark

jwt.secret.key =q2NpY29sZSBzdGFja2V4Y2hhbmdlIGludGVybmF0aW9uYWxpemF0aW9uIHJvYm90cyBpbg==

#razorpay configuration
razorpay_key = ${RAZORPAY_KEY}
razorpay_secret = ${RAZORPAY_SECRET}

#paypal configuration
paypal:
    client-id: AS79k9oFEh1QLvb2cKGaPnxzA8TM4lU-S9ujnALevPJR4czQMbVfrE0SD9k01QYOHR6gmiQh398CMdh5
    client-secret:EI5wUuqC-iWvaYc8GIxqf-t8baWh69VIlORrk2LKho19XlMrrgyIIc_DaSyFJW3-tPR2x5VYBTztJJnV
    mode:sandbox # Use#sanbox' for testing and 'lie' for Production 